apiVersion: v1
kind: Pod
metadata:
  name: heimdall-pod
  annotations:
    io.containers.autoupdate/heimdall: registry
  labels:
    app: heimdall
spec:
  containers:
  - name: heimdall
    image: ghcr.io/linuxserver/heimdall:latest
    resources: {}
    env:
    - name: TZ
      value: America/New_York
    - name: PGID
      value: "1000"
    - name: PUID
      value: "1000"
    securityContext:
      allowPrivilegeEscalation: true
    volumeMounts:
    - name: heimdall-mnt
      mountPath: /config:z
  restartPolicy: OnFailure
  volumes:
  - name: heimdall-mnt
    hostPath:
      path: /container-storage/heimdall
      type: Directory
