apiVersion: v1
kind: Pod
metadata:
  name: homebridge-pod
  annotations:
    bind-mount-options: /mnt/storage/homebridge:z
    io.container.autoupdate/homebridge: registry
  labels:
    app: homebridge
spec:
  containers:
  - name: homebridge
    image: docker.io/homebridge/homebridge:latest
    resources: {}
    env:
    - name: HOMEBRIDGE_CONFIG_UI
      value: "1"
    - name: HOMEBRIDGE_CONFIG_UI_PORT
      value: "8581"
    - name: TZ
      value: America/New_York
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - CAP_MKNOD
        - CAP_NET_ADMIN
        - CAP_NET_RAW
    livenessProbe:
      httpGet:
        path: /api
        port: 8581
      periodSeconds: 10
      initialDelaySeconds: 5
    volumeMounts:
    - name: homebridge-mnt
      mountPath: /homebridge
  hostNetwork: true
  restartPolicy: OnFailure
  volumes:
  - name: homebridge-mnt
    hostPath:
      path: /mnt/storage/homebridge
      type: Directory
