apiVersion: v1
kind: Pod
metadata:
  name: homebridge
  annotations:
    bind-mount-options: /container-storage/homebridge:z
    io.container.autoupdate/homebridge: registry
  labels:
    app: homebridge
spec:
  containers:
  - name: homebridge
    image: docker.io/homebridge/homebridge:latest
    env:
    - name: HOMEBRIDGE_CONFIG_UI
      value: "1"
    - name: HOMEBRIDGE_CONFIG_UI_PORT
      value: "8581"
    - name: TZ
      value: America/New_York
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - CAP_MKNOD
        - CAP_NET_ADMIN
        - CAP_NET_RAW
    volumeMounts:
    - name: homebridge-mnt
      mountPath: /homebridge
      resources: {}
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /container-storage/homebridge
      type: Directory
    name: homebridge-mnt
